---
- name: Install required packages
  apt:
    update_cache: yes
    name: "{{ nycdb_packages }}"

- name: Add postgres signing key
  apt_key:
    data: "{{ lookup('file', 'ACCC4CF8.asc') }}"
    state: present

- name: Add postgres apt
  apt_repository:
    repo: "{{ postgres_apt_repository }}"
    state: present

- name: Install postgres packages
  apt:
    update_cache: yes
    name: "{{ postgres_packages }}"

- name: Install psycopg2
  become: yes
  pip:
    name: psycopg2
    executable: /usr/bin/pip3
    extra_args: --no-binary psycopg2

- name: Setup postgres db
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
      name: "{{ nycdb_database_name }}"
      
- name: Create database user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user: 
    db: "{{ nycdb_database_name}}"
    name: "{{ nycdb_database_user }}" 
    password: "{{ nycdb_database_password }}"
    encrypted: yes
    priv: ALL

- name: Ensure database user does not have unnecessary privileges
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ nycdb_database_user }}" 
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    
- name: Create /srv/nyc-db
  file:
    path: /srv/nyc-db
    state: directory
    owner: "{{ nycdb_user }}"
    
- name: Clone the nyc-db repo
  become: yes
  become_user: "{{ nycdb_user }}"
  vars:
    ansible_ssh_pipelining: true
  git:
    repo: https://github.com/aepyornis/nyc-db.git
    dest: /srv/nyc-db
    force: true
    version: master

- name: install python3 packages
  become: yes
  pip:
    requirements: /srv/nyc-db/src/requirements.txt
    executable: /usr/bin/pip3
    extra_args: --no-binary psycopg2

- name: install nycdb
  become: yes
  pip:
    name: file:///srv/nyc-db/src
