- name: install node
  include_role:
    name: geerlingguy.nodejs
  vars:
    nodejs_version: "8.x"
  tags: sqlpad-setup


- name: install sqlpad
  npm:
    name: sqlpad
    global: yes
    production: yes
  tags: sqlpad-setup

    
- name: create sqlpad group
  group:
    name: sqlpad
    state: present
  tags: sqlpad-setup


- name: Create sqlpad user
  user:
    name: sqlpad
    groups: sqlpad
    append: yes
    shell: /bin/bash
  tags: sqlpad-setup


- name: create sqlpad postgresql user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ nycdb_database_name }}"
    name: "{{ sqlpad_db_user }}"
    password: "{{ sqlpad_db_password }}"
    priv: CONNECT
    encrypted: yes
    role_attr_flags: NOSUPERUSER,NOCREATEDB


- name: grant usage on schema public
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_privs:
    db: "{{ nycdb_database_name }}"
    role: "{{ sqlpad_db_user }}"
    type: schema
    state: present
    privs: USAGE
    objs: public

- name: grant select privilages for sqlpad PG user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_privs:
    db: "{{ nycdb_database_name }}"
    role: "{{ sqlpad_db_user }}"
    type: table
    state: present
    privs: SELECT
    objs: ALL_IN_SCHEMA
    
- name: ensure sqlpad does not have write permissions
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_privs:
    db: "{{ nycdb_database_name }}"
    state: absent
    roles: "{{ sqlpad_db_user }}"
    privs: INSERT,UPDATE,DELETE,TRUNCATE
    type: table
    objs: ALL_IN_SCHEMA


- name: Install sqlpad systemd unit file
  copy:
    src: sqlpad.service
    dest: /etc/systemd/system/sqlpad.service
  tags: sqlpad-setup
      
- name: start sqlpad service
  systemd:
    state: started
    name: sqlpad
    daemon_reload: yes
  tags: sqlpad-setup
