---
- name: Setup NYC-DB
  hosts: nycdb
  become: yes

  pre_tasks:
    - name: load secret vars from ~/nycdb.yml
      include_vars:
        file: ~/nycdb.yml
      tags: always

  roles:
   - common
   - nycdb
   - api
   - sqlpad

