sudo: true
dist: xenial

language: python
python:
  - 3.6
  - 3.7
  
  
services:
  - docker

before_install:
  - docker pull postgres:11
  - docker run -p 127.0.0.1:7777:5432 --name nycdb_test -e POSTGRES_USER=nycdb -e POSTGRES_PASSWORD=nycdb -e POSTGRES_DB=nycdb_test -d postgres:11
  - ./src/scripts/wait-for-pg.sh

install:
  - pip install -r src/requirements.txt

script:
  - cd src && pytest
