---
nycdb_packages:
  - sudo
  - wget
  - curl
  - zip
  - unzip
  - bzip2
  - git
  - tmux
  - mosh
  - htop
  - build-essential
  - python3
  - python3-pip
  - python3-dev
  - python3-venv
  - python3-setuptools

#  - python3-psycopg2
postgres_apt_repository: "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"

postgres_packages:
  - postgresql-11
  - postgresql-client-11
  - postgresql-contrib-11
  - libpq-dev
