- name: Install doc requirements
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ item }}"
  with_items:
    - pandoc
       
- name: Create /srv/nyc-db
  file:
    path: /srv/nyc-db
    state: directory
    owner: "{{ nycdb_user }}"
    
- name: Clone the nyc-db repo
  become: yes
  become_user: "{{ nycdb_user }}"
  vars:
    ansible_ssh_pipelining: true
  git:
    repo: https://github.com/aepyornis/nyc-db.git
    dest: /srv/nyc-db
    version: master

- name: Build docs
  become: yes
  become_user: "{{ nycdb_user }}"
  vars:
    ansible_ssh_pipelining: true
  make:
    chdir: /srv/nyc-db/server
    target: index.html

- name: copy index.html to /var/www/nycdb
  copy:
    src: /srv/nyc-db/server/index.html
    dest: /var/www/nycdb/index.html
    remote_src: yes
    owner: nycdb
    group: nycdb
    mode: 0644
    
